import type { Game, Tournament, Mission, Transaction, User, DailyStreak, Notification, Reward } from '@/types'

export const mockUser: User = {
  id: '1',
  email: 'player@neonnexus.com',
  username: 'NeonPlayer',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NeonPlayer',
  balance: 12500,
  xp: 4250,
  level: 5,
  vipTier: 'gold',
  createdAt: new Date('2024-01-15'),
}

export const mockGames: Game[] = [
  {
    id: '1',
    name: 'Cyber Dreams',
    provider: 'NetEnt',
    thumbnail: 'https://picsum.photos/seed/game1/400/533',
    rtp: 96.5,
    volatility: 'medium',
    category: 'slots',
    isFavorite: false,
    playerCount: 1243,
    isPopular: true,
  },
  {
    id: '2',
    name: 'Neon Blitz',
    provider: 'Pragmatic',
    thumbnail: 'https://picsum.photos/seed/game2/400/533',
    rtp: 95.2,
    volatility: 'high',
    category: 'slots',
    isFavorite: true,
    playerCount: 892,
    isNew: true,
  },
  {
    id: '3',
    name: 'Stellar Surge',
    provider: 'Play\'n GO',
    thumbnail: 'https://picsum.photos/seed/game3/400/533',
    rtp: 94.8,
    volatility: 'high',
    category: 'jackpot',
    isFavorite: false,
    playerCount: 567,
    jackpotAmount: 250000,
  },
  {
    id: '4',
    name: 'Quantum Rush',
    provider: 'Red Tiger',
    thumbnail: 'https://picsum.photos/seed/game4/400/533',
    rtp: 97.1,
    volatility: 'low',
    category: 'high-rtp',
    isFavorite: false,
    playerCount: 2103,
    isPopular: true,
  },
  {
    id: '5',
    name: 'Meteor Crash',
    provider: 'BGaming',
    thumbnail: 'https://picsum.photos/seed/game5/400/533',
    rtp: 99.0,
    volatility: 'high',
    category: 'crash',
    isFavorite: true,
    playerCount: 3421,
    isPopular: true,
  },
  {
    id: '6',
    name: 'Cosmic Fortune',
    provider: 'Yggdrasil',
    thumbnail: 'https://picsum.photos/seed/game6/400/533',
    rtp: 96.0,
    volatility: 'medium',
    category: 'slots',
    isFavorite: false,
    playerCount: 789,
  },
  {
    id: '7',
    name: 'Aurora Spins',
    provider: 'Spinomenal',
    thumbnail: 'https://picsum.photos/seed/game7/400/533',
    rtp: 95.5,
    volatility: 'medium',
    category: 'bonus-buy',
    isFavorite: false,
    playerCount: 456,
    isNew: true,
  },
  {
    id: '8',
    name: 'Galaxy Live',
    provider: 'Evolution',
    thumbnail: 'https://picsum.photos/seed/game8/400/533',
    rtp: 98.5,
    volatility: 'low',
    category: 'live',
    isFavorite: false,
    playerCount: 1876,
    isPopular: true,
  },
  {
    id: '9',
    name: 'Nebula Night',
    provider: 'Quickspin',
    thumbnail: 'https://picsum.photos/seed/game9/400/533',
    rtp: 94.2,
    volatility: 'high',
    category: 'slots',
    isFavorite: false,
    playerCount: 321,
  },
  {
    id: '10',
    name: 'Pulsar Party',
    provider: 'Amatic',
    thumbnail: 'https://picsum.photos/seed/game10/400/533',
    rtp: 96.8,
    volatility: 'medium',
    category: 'slots',
    isFavorite: true,
    playerCount: 654,
  },
  {
    id: '11',
    name: 'Void Voyager',
    provider: 'Thunderkick',
    thumbnail: 'https://picsum.photos/seed/game11/400/533',
    rtp: 97.3,
    volatility: 'medium',
    category: 'slots',
    isFavorite: false,
    playerCount: 432,
    isNew: true,
  },
  {
    id: '12',
    name: 'Supernova Strike',
    provider: 'Relax Gaming',
    thumbnail: 'https://picsum.photos/seed/game12/400/533',
    rtp: 95.9,
    volatility: 'high',
    category: 'jackpot',
    isFavorite: false,
    playerCount: 876,
    jackpotAmount: 180000,
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    type: 'deposit',
    amount: 500,
    status: 'completed',
    description: 'Wallet Deposit',
    createdAt: new Date('2024-02-10T14:30:00'),
  },
  {
    id: '2',
    type: 'win',
    amount: 1250,
    status: 'completed',
    description: 'Won on Cyber Dreams',
    createdAt: new Date('2024-02-09T18:45:00'),
  },
  {
    id: '3',
    type: 'bonus',
    amount: 100,
    status: 'completed',
    description: 'Daily Login Bonus',
    createdAt: new Date('2024-02-09T08:00:00'),
  },
  {
    id: '4',
    type: 'withdraw',
    amount: 200,
    status: 'completed',
    description: 'Withdrawal to Bank',
    createdAt: new Date('2024-02-08T10:15:00'),
  },
  {
    id: '5',
    type: 'bet',
    amount: -50,
    status: 'completed',
    description: 'Bet on Neon Blitz',
    createdAt: new Date('2024-02-07T16:20:00'),
  },
]

export const mockTournaments: Tournament[] = [
  {
    id: '1',
    name: 'Neon Championship',
    description: 'Weekly slot tournament with massive prize pool',
    prizePool: 50000,
    entryFee: 0,
    playerCount: 1245,
    maxPlayers: 5000,
    status: 'active',
    startsAt: new Date('2024-02-08T00:00:00'),
    endsAt: new Date('2024-02-15T23:59:59'),
    gameCategory: 'slots',
  },
  {
    id: '2',
    name: 'Crash Kings',
    description: 'Daily crash game showdown',
    prizePool: 5000,
    entryFee: 100,
    playerCount: 432,
    maxPlayers: 1000,
    status: 'active',
    startsAt: new Date('2024-02-12T12:00:00'),
    endsAt: new Date('2024-02-12T23:59:59'),
    gameCategory: 'crash',
  },
  {
    id: '3',
    name: 'VIP Prestige Cup',
    description: 'Exclusive tournament for Gold+ members',
    prizePool: 25000,
    entryFee: 500,
    playerCount: 89,
    maxPlayers: 200,
    status: 'upcoming',
    startsAt: new Date('2024-02-20T18:00:00'),
    endsAt: new Date('2024-02-22T23:59:59'),
    gameCategory: 'slots',
  },
  {
    id: '4',
    name: 'Jackpot Hunter',
    description: 'Play jackpot games to climb the leaderboard',
    prizePool: 100000,
    entryFee: 0,
    playerCount: 2156,
    maxPlayers: 10000,
    status: 'active',
    startsAt: new Date('2024-02-05T00:00:00'),
    endsAt: new Date('2024-02-19T23:59:59'),
    gameCategory: 'jackpot',
  },
]

export const mockMissions: Mission[] = [
  {
    id: '1',
    title: 'Spin Master',
    description: 'Play 50 spins on any slot game',
    progress: 35,
    target: 50,
    reward: 100,
    isDaily: true,
    isCompleted: false,
    isClaimed: false,
    expiresAt: new Date('2024-02-13T23:59:59'),
  },
  {
    id: '2',
    title: 'Win Streak',
    description: 'Win 5 games in a row',
    progress: 3,
    target: 5,
    reward: 250,
    isDaily: true,
    isCompleted: false,
    isClaimed: false,
    expiresAt: new Date('2024-02-13T23:59:59'),
  },
  {
    id: '3',
    title: 'Big Winner',
    description: 'Win a single spin of 100x or more',
    progress: 0,
    target: 1,
    reward: 500,
    isDaily: true,
    isCompleted: false,
    isClaimed: false,
    expiresAt: new Date('2024-02-13T23:59:59'),
  },
  {
    id: '4',
    title: 'Tournament Hero',
    description: 'Play in 3 tournaments this week',
    progress: 1,
    target: 3,
    reward: 1000,
    isDaily: false,
    isCompleted: false,
    isClaimed: false,
    expiresAt: new Date('2024-02-18T23:59:59'),
  },
  {
    id: '5',
    title: 'VIP Explorer',
    description: 'Reach VIP Gold status',
    progress: 1,
    target: 1,
    reward: 5000,
    isDaily: false,
    isCompleted: false,
    isClaimed: false,
    expiresAt: new Date('2024-03-01T23:59:59'),
  },
  {
    id: '6',
    title: 'Game Collector',
    description: 'Try 10 different games',
    progress: 7,
    target: 10,
    reward: 300,
    isDaily: false,
    isCompleted: false,
    isClaimed: false,
    expiresAt: new Date('2024-02-18T23:59:59'),
  },
]

export const mockDailyStreak: DailyStreak = {
  currentDay: 4,
  totalDays: 7,
  nextReward: 200,
  canClaim: true,
  lastClaimedAt: new Date('2024-02-11T08:00:00'),
}

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'success',
    title: 'Welcome Bonus!',
    message: 'You received 1000 coins bonus',
    isRead: false,
    createdAt: new Date('2024-02-12T10:00:00'),
  },
  {
    id: '2',
    type: 'info',
    title: 'Daily Reward',
    message: 'Come back tomorrow for more rewards',
    isRead: false,
    createdAt: new Date('2024-02-12T08:00:00'),
  },
  {
    id: '3',
    type: 'info',
    title: 'Tournament Started',
    message: 'Neon Championship is now live!',
    isRead: true,
    createdAt: new Date('2024-02-08T00:00:00'),
  },
]

export const mockRewards: Reward[] = [
  {
    id: '1',
    type: 'xp',
    amount: 500,
    description: 'Level up reward',
    claimedAt: new Date('2024-02-10T15:30:00'),
  },
  {
    id: '2',
    type: 'bonus',
    amount: 100,
    description: 'Daily login bonus',
    claimedAt: new Date('2024-02-09T08:00:00'),
  },
  {
    id: '3',
    type: 'free spins',
    amount: 50,
    description: 'Free spins on Cyber Dreams',
    claimedAt: new Date('2024-02-08T12:00:00'),
    expiresAt: new Date('2024-02-15T12:00:00'),
  },
]

export const vipTiers = [
  {
    tier: 'bronze' as const,
    name: 'Bronze',
    minXP: 0,
    color: '#CD7F32',
    benefits: ['Weekly bonus', 'Basic support', 'Birthday gift'],
  },
  {
    tier: 'silver' as const,
    name: 'Silver',
    minXP: 5000,
    color: '#C0C0C0',
    benefits: ['2x weekly bonus', 'Priority support', 'Monthly cashback 1%'],
  },
  {
    tier: 'gold' as const,
    name: 'Gold',
    minXP: 20000,
    color: '#FFD700',
    benefits: ['3x weekly bonus', 'VIP support', 'Monthly cashback 2%', 'Exclusive tournaments'],
  },
  {
    tier: 'platinum' as const,
    name: 'Platinum',
    minXP: 50000,
    color: '#E5E4E2',
    benefits: ['5x weekly bonus', 'Dedicated manager', 'Monthly cashback 3%', 'Early access to games'],
  },
  {
    tier: 'diamond' as const,
    name: 'Diamond',
    minXP: 100000,
    color: '#B9F2FF',
    benefits: ['10x weekly bonus', 'Personal concierge', 'Monthly cashback 5%', 'Luxury gifts'],
  },
  {
    tier: 'obsidian' as const,
    name: 'Obsidian',
    minXP: 500000,
    color: '#8B5CF6',
    benefits: ['Unlimited bonus', '24/7 white-glove service', 'Monthly cashback 10%', 'Custom rewards'],
  },
]

export const heroCarouselItems = [
  {
    id: '1',
    title: 'Claim Your Free Spins',
    description: 'Get 50 free spins on Cyber Dreams!',
    cta: 'Claim Now',
    ctaLink: '/games/1',
    badge: 'Limited Time',
    badgeColor: 'purple',
    backgroundImage: 'https://picsum.photos/seed/hero1/1200/600',
    endsAt: new Date('2024-02-14T23:59:59'),
  },
  {
    id: '2',
    title: 'Neon Championship',
    description: '$50,000 prize pool - Join now!',
    cta: 'Enter Tournament',
    ctaLink: '/tournaments/1',
    badge: 'Live Now',
    badgeColor: 'green',
    backgroundImage: 'https://picsum.photos/seed/hero2/1200/600',
    endsAt: new Date('2024-02-15T23:59:59'),
  },
  {
    id: '3',
    title: 'VIP Weekend',
    description: 'Double XP and exclusive rewards',
    cta: 'Unlock Benefits',
    ctaLink: '/vip',
    badge: 'VIP Only',
    badgeColor: 'gold',
    backgroundImage: 'https://picsum.photos/seed/hero3/1200/600',
    endsAt: new Date('2024-02-18T23:59:59'),
  },
]

export const gameCategories = [
  { id: 'popular', name: 'Popular', icon: 'TrendingUp' },
  { id: 'new', name: 'New', icon: 'Sparkles' },
  { id: 'slots', name: 'Slots', icon: 'Gamepad2' },
  { id: 'crash', name: 'Crash', icon: 'Rocket' },
  { id: 'live', name: 'Live', icon: 'Tv' },
  { id: 'high-rtp', name: 'High RTP', icon: 'Target' },
  { id: 'jackpot', name: 'Jackpot', icon: 'Trophy' },
  { id: 'bonus-buy', name: 'Bonus Buy', icon: 'ShoppingCart' },
]

export const liveWinners = [
  { username: 'NeonKing', amount: 2500, game: 'Cyber Dreams' },
  { username: 'StarGazer99', amount: 1800, game: 'Neon Blitz' },
  { username: 'CosmicPlayer', amount: 4200, game: 'Meteor Crash' },
  { username: 'GalaxyWin', amount: 950, game: 'Quantum Rush' },
  { username: 'AstroSpin', amount: 3200, game: 'Stellar Surge' },
  { username: 'VoidHunter', amount: 1500, game: 'Cosmic Fortune' },
  { username: 'PulsarKing', amount: 2100, game: 'Aurora Spins' },
  { username: 'NebulaWins', amount: 750, game: 'Galaxy Live' },
]